import collections
my_deque = collections.deque()
my_deque.append(5)
my_deque.append(60)
my_deque.append(77)
my_deque.append(511)
my_deque.append(25)
my_deque.rotate()
print(my_deque)
my_deque.rotate(2)
print(my_deque)
my_deque.append(-3)
my_deque.append(3)
my_deque.rotate()
print(my_deque)
my_deque.rotate(-1)
print(my_deque)